---
namespace: hostinger
name: common
repository: https://github.com/hostinger/ansible-collection-common
version: 0.6.1 # x-release-please-version
readme: README.md
authors:
  - konradasb
description: Collection of Ansible roles for configuring Linux servers used internally at Hostinger.
license:
  - MIT
dependencies:
  community.general: ">=4.5.0"
tags:
  - linux
