---
galaxy_info:
  role_name: rclone
  author: hostinger
  description: Ansible role for configuring rclone.
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
  - rclone
