---
- name: Fail when unsupported architecture
  ansible.builtin.fail:
    msg: "Unsupported architecture"
  when:
    - tc_redirect_tap_arch not in ['amd64', 'arm64']

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: 0755
    state: directory
    owner: "{{ tc_redirect_tap_owner }}"
    group: "{{ tc_redirect_tap_group }}"
  with_items:
    - "{{ tc_redirect_tap_dir }}"
    - "{{ tc_redirect_tap_install_dir }}"
    - "{{ tc_redirect_tap_bin_dir }}"

- name: Download binary
  ansible.builtin.get_url:
    url: "{{ tc_redirect_tap_url }}"
    dest: "{{ tc_redirect_tap_install_dir }}/tc-redirect-tap"
    mode: 0755
    owner: "{{ tc_redirect_tap_owner }}"
    group: "{{ tc_redirect_tap_group }}"
    timeout: 30

- name: Create symlink to binaries
  ansible.builtin.file:
    src: "{{ tc_redirect_tap_install_dir }}/tc-redirect-tap"
    dest: "{{ tc_redirect_tap_bin_dir }}/tc-redirect-tap"
    mode: 0755
    owner: "{{ tc_redirect_tap_owner }}"
    group: "{{ tc_redirect_tap_group }}"
    state: link
