---
- name: Login to container registry
  environment:
    REGISTRY_PASSWORD: "{{ nerdctl_login_password }}"
  ansible.builtin.shell: nerdctl login -u {{ nerdctl_login_username }} -p "${REGISTRY_PASSWORD}" {{ nerdctl_login_registry_url }}
  changed_when: false
  when:
    - nerdctl_login_registry_url | length > 0
