---
registry_version: 2.8.3
registry_url: |
  https://github.com/distribution/distribution/releases/download/v{{ registry_version }}/registry_{{ registry_version }}_{{ registry_os }}_{{ registry_arch }}.tar.gz
registry_arch: amd64
registry_os: linux
registry_install_dir: /opt/registry/{{ registry_version }}
registry_owner: root
registry_group: root
registry_config_dir: /etc/registry
registry_name: default
registry_config:
  version: 0.1
  log:
    level: debug
  storage:
    filesystem:
        rootdirectory: /var/lib/registry
  http:
    addr: localhost:5000
    secret: asecretforlocaldevelopment
