---
galaxy_info:
  role_name: registry
  author: hostinger
  description: Ansible role to install and configure distribution/registry
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
  - name: Fedora
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
  - registry
